### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by kusiLaw** [shyusu4/To-Do-List#5]
Highlight :heavy_check_mark: 
- Nice UI design 
- Follow javascript best practices
- Meet all the requirement 

Optional 
![Screenshot from 2022-08-25 07-16-08](https://user-images.githubusercontent.com/52538840/186600824-26363b6b-284c-402a-91b6-b254bc69c756.png)
I found a bug when I user marks a list as complete and tries to add a new list, it opens a text input field which can't be closed and besides marking the next list marks the item to the next.

I would recommend if you could check that and fix it. thank you

**Comment by degisew** [comment]
Hi @shyusu4 

Great job so far 👏 

**Optional Sugestions**

I kindly suggest that it is better to make the trash icon visible when the user clicks the popup icon.

**Comment by shyusu4** [comment]
Hi @kusiLaw and @degisew 😄
Thank you for your great suggestions! I will make sure to implement them in my code.
